In [1]:
import torch

In [2]:
import numpy as np

In [3]:
inputs = np.array([[73,67,43],
                  [91,88,64],
                  [87,134,58],
                  [102,43,37],
                   [69,96,70]],dtype='float32')

In [4]:
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

In [5]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [6]:
# weights and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.1680, -1.2553, -0.1904],
        [ 0.1047, -0.2434, -1.2790]], requires_grad=True)
tensor([ 0.2232, -0.3937], requires_grad=True)


In [7]:
# @ for matrix multiplication 
# .t() for transpose
def model(x):
    return x @ w.t() + b

In [8]:
pre = model(inputs)
pre

tensor([[-104.3344,  -64.0534],
        [-137.7190,  -94.1382],
        [-193.6504,  -98.0789],
        [ -77.9343,  -47.5026],
        [-145.2094, -106.0621]], grad_fn=<AddBackward0>)

In [9]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [10]:
# Loss Function
# mean squred error
# .numel() returns total elements in tensor
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff**2)/diff.numel()

In [11]:
diff = targets - pre
diff_sqr = diff**2
torch.sum(diff_sqr)

tensor(410130.5312, grad_fn=<SumBackward0>)

In [12]:
torch.sum(diff_sqr)/diff.numel()

tensor(41013.0547, grad_fn=<DivBackward0>)

In [13]:
loss = mse(targets,pre)
loss

tensor(41013.0547, grad_fn=<DivBackward0>)

In [14]:
# compute gradient
loss.backward()


In [15]:
print(w)
print(w.grad)

tensor([[-0.1680, -1.2553, -0.1904],
        [ 0.1047, -0.2434, -1.2790]], requires_grad=True)
tensor([[-17225.6367, -20002.0234, -12019.6699],
        [-14359.1787, -16471.5781, -10107.3320]])


In [16]:
print(b)
print(b.grad)

tensor([ 0.2232, -0.3937], requires_grad=True)
tensor([-207.9695, -173.9670])


In [17]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [18]:
preds = model(inputs)
preds

tensor([[-104.3344,  -64.0534],
        [-137.7190,  -94.1382],
        [-193.6504,  -98.0789],
        [ -77.9343,  -47.5026],
        [-145.2094, -106.0621]], grad_fn=<AddBackward0>)

In [19]:
loss = mse(preds,targets)
loss

tensor(41013.0547, grad_fn=<DivBackward0>)

In [20]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-17225.6367, -20002.0234, -12019.6699],
        [-14359.1787, -16471.5781, -10107.3320]])
tensor([-207.9695, -173.9670])


In [21]:
# adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad*1e-5
    b -= b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()


In [22]:
print(w)
print(b)

tensor([[ 0.0043, -1.0553, -0.0702],
        [ 0.2483, -0.0787, -1.1779]], requires_grad=True)
tensor([ 0.2253, -0.3920], requires_grad=True)


In [23]:
pred = model(inputs)
loss = mse(pred,targets)
print(loss)

tensor(28074.0742, grad_fn=<DivBackward0>)


In [24]:
# train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [25]:
preds = model(inputs)
loss = mse(preds,targets)
loss

tensor(459.5436, grad_fn=<DivBackward0>)

In [26]:
preds

tensor([[ 63.9831,  76.2807],
        [ 86.7874,  93.8006],
        [ 97.3152, 138.9806],
        [ 60.4816,  71.0000],
        [ 86.9422,  87.2786]], grad_fn=<AddBackward0>)

In [27]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [28]:
# further traning
# train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


In [29]:
preds = model(inputs)
loss = mse(preds,targets)
loss

tensor(191.3354, grad_fn=<DivBackward0>)

In [30]:
print(preds)
print(targets)

tensor([[ 60.8211,  73.9230],
        [ 84.3997,  93.0100],
        [107.8291, 144.5688],
        [ 42.0803,  57.3789],
        [ 93.5262,  93.8519]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [31]:
# Linear regression using built in functions

In [32]:
import torch.nn as nn

In [33]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [34]:
inputs = np.array([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]],dtype='float32')

In [35]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [36]:
targets = np.array([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]],dtype='float32')

In [37]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [38]:
from torch.utils.data import TensorDataset

In [39]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [40]:
train_ds[:]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [41]:
from torch.utils.data import DataLoader

In [42]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [43]:
for xb,yb in train_dl:
    print('Batch:')
    print(xb)
    print(yb)
    break

Batch:
tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.]])
tensor([[119., 133.],
        [103., 119.],
        [119., 133.],
        [ 22.,  37.],
        [119., 133.]])


In [44]:
for xb,yb in train_dl:
    print('Batch:')
    print(xb)
    print(yb)


Batch:
tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [103., 119.]])
Batch:
tensor([[ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.]])
tensor([[ 81., 101.],
        [ 56.,  70.],
        [ 56.,  70.],
        [ 22.,  37.],
        [ 81., 101.]])
Batch:
tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[103., 119.],
        [119., 133.],
        [ 22.,  37.],
        [ 81., 101.],
        [119., 133.]])


In [45]:
# from nn.Linear
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3371, -0.1282,  0.4001],
        [-0.3368,  0.2723,  0.0342]], requires_grad=True)
Parameter containing:
tensor([-0.3931, -0.0981], requires_grad=True)


In [46]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3371, -0.1282,  0.4001],
         [-0.3368,  0.2723,  0.0342]], requires_grad=True),
 Parameter containing:
 tensor([-0.3931, -0.0981], requires_grad=True)]

In [47]:
preds = model(inputs)
preds

tensor([[ 32.8295,  -4.9666],
        [ 44.6066,  -4.5916],
        [ 34.9594,   9.0779],
        [ 43.2835, -21.4747],
        [ 38.5641,   5.2016],
        [ 32.8295,  -4.9666],
        [ 44.6066,  -4.5916],
        [ 34.9594,   9.0779],
        [ 43.2835, -21.4747],
        [ 38.5641,   5.2016],
        [ 32.8295,  -4.9666],
        [ 44.6066,  -4.5916],
        [ 34.9594,   9.0779],
        [ 43.2835, -21.4747],
        [ 38.5641,   5.2016]], grad_fn=<AddmmBackward>)

In [48]:
import torch.nn.functional as F

In [49]:
loss_fn = F.mse_loss

In [50]:
loss = loss_fn(model(inputs),targets)
loss

tensor(6202.4751, grad_fn=<MseLossBackward>)

In [51]:
?nn.Linear
# describe all detail

In [52]:
# optimizer
opt = torch.optim.SGD(model.parameters(),lr=1e-5)


In [53]:
def fit(num_epochs,model,loss_fn,opt):
    # repeat for given number of epochs
    for epoch in range(num_epochs):
        # Train with batches of data
        for xb,yb in train_dl:
            # 1. generate predictions
            pred = model(xb)
            # 2. calculate loss
            loss = loss_fn(pred,yb)
            # 3. compute gradients
            loss.backward()
            # 4. update perameters using gradients
            opt.step()
            # 5. reset gradients to zero
            opt.zero_grad()
            
        # print the process
        if(epoch+1) % 10 ==0:
            print('Epoch[{}/{}], Loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [54]:
fit(100,model,loss_fn,opt)

Epoch[10/100], Loss:366.6393
Epoch[20/100], Loss:251.1582
Epoch[30/100], Loss:288.3726
Epoch[40/100], Loss:149.0114
Epoch[50/100], Loss:103.3164
Epoch[60/100], Loss:110.5122
Epoch[70/100], Loss:70.0313
Epoch[80/100], Loss:31.9796
Epoch[90/100], Loss:33.1449
Epoch[100/100], Loss:13.4003


In [55]:
preds = model(inputs)
preds

tensor([[ 58.3666,  71.1948],
        [ 82.7180,  98.0481],
        [114.5672, 138.0532],
        [ 29.2382,  41.4896],
        [ 98.0460, 111.9064],
        [ 58.3666,  71.1948],
        [ 82.7180,  98.0481],
        [114.5672, 138.0532],
        [ 29.2382,  41.4896],
        [ 98.0460, 111.9064],
        [ 58.3666,  71.1948],
        [ 82.7180,  98.0481],
        [114.5672, 138.0532],
        [ 29.2382,  41.4896],
        [ 98.0460, 111.9064]], grad_fn=<AddmmBackward>)

In [56]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])