In [1]:
import torch

In [2]:
t1 = torch.tensor(3.)

In [3]:
t1

tensor(3.)

In [4]:
t2 = torch.tensor([2,3,4,5.])

In [5]:
t2

tensor([2., 3., 4., 5.])

In [6]:
t3 = torch.tensor([[1,2,3,4],[11,12,13,14,15]])

ValueError: expected sequence of length 4 at dim 1 (got 5)

In [7]:
t3 = torch.tensor([[1,2,3,4],[11,12,13,14.]])

In [8]:
t3

tensor([[ 1.,  2.,  3.,  4.],
        [11., 12., 13., 14.]])

In [9]:
t4 = torch.tensor([[[2,4,6,8],[1,3,5,7]],[[12,14,16,18],[11,13,15,17]]])

In [10]:
t4

tensor([[[ 2,  4,  6,  8],
         [ 1,  3,  5,  7]],

        [[12, 14, 16, 18],
         [11, 13, 15, 17]]])

In [11]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([2, 4])
torch.Size([2, 2, 4])


In [12]:
import numpy as np


In [13]:
x = np.random.randint(0,100,10)

In [14]:
x

array([63, 18, 54, 60, 83, 89, 23, 96, 75,  7])

In [15]:
ten_x = torch.tensor(x)

In [16]:
ten_x

tensor([63, 18, 54, 60, 83, 89, 23, 96, 75,  7], dtype=torch.int32)

In [17]:
ten_x_not_copy = torch.as_tensor(x)

In [18]:
ten_x_not_copy

tensor([63, 18, 54, 60, 83, 89, 23, 96, 75,  7], dtype=torch.int32)

In [30]:
# import torch.nn as nn 

In [31]:
m = torch.tensor([[1,2,3,4.]])

In [32]:
x = torch.tensor([[3,4,5,6.]],requires_grad=True)

In [33]:
y = m*x

In [34]:
y

tensor([[ 3.,  8., 15., 24.]], grad_fn=<MulBackward0>)

In [35]:
x.diff()

tensor([[1., 1., 1.]], grad_fn=<SubBackward0>)

In [36]:
y.diff()

tensor([[5., 7., 9.]], grad_fn=<SubBackward0>)

In [39]:
# x.grad()

In [40]:
# m.grad()

In [41]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)

In [42]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [43]:
y.backward()

In [46]:
print(x.grad)

None


In [47]:
w.grad

tensor(3.)

In [48]:
b.grad

tensor(1.)

In [86]:
a = torch.tensor([[1.,2],[5,6]])
b = torch.tensor([[11.,12],[15,16]],requires_grad=True)
c = torch.tensor([[21.,22],[25,26]],requires_grad=True)

In [87]:
a.shape

torch.Size([2, 2])

In [88]:
b.shape

torch.Size([2, 2])

In [89]:
b*a

tensor([[11., 24.],
        [75., 96.]], grad_fn=<MulBackward0>)

In [90]:
x = a*b + c
x

tensor([[ 32.,  46.],
        [100., 122.]], grad_fn=<AddBackward0>)

In [92]:
import numpy as np

In [94]:
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [96]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [98]:
y = torch.tensor(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [99]:
x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [100]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [124]:
w = torch.tensor(4.,requires_grad=True)
x = torch.tensor([[1,2],[3,4.]])
b = torch.tensor(5.)

In [125]:
y = w*x + b

In [126]:
y

tensor([[ 9., 13.],
        [17., 21.]], grad_fn=<AddBackward0>)